version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: taski
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/taski
    volumes:
      - static:/app/static
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    volumes:
      - static:/frontend_static
    command: sh -c "npm run build && cp -r /app/build/* /frontend_static/"

  nginx:
    image: nginx:alpine
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

volumes:
  static:
  db_data:
