volumes:
  pg_data:
  static:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: dreamcat18/taski_backend:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
  frontend:
    image: dreamcat18/taski_frontend:latest
    env_file: .env
    volumes:
      - static:/static
    command: cp -r /app/build/. /static/
  gateway:
    image: dreamcat18/taski_gateway:latest
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static
    ports:
      - "8000:80"
