volumes:
  pg_data_production:
  static_volume:


services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: dreamcat18/taski_backend:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
  frontend:
    image: dreamcat18/taski_frontend:latest
    env_file: .env
    volumes:
      - static_volume:/frontend_static
    command: cp -r /app/build/. /frontend_static/
  gateway:
    image: dreamcat18/taski_gateway:latest
    depends_on:
      - backend
      - frontend
    volumes:
      - static_volume:/staticfiles
    ports:
      - "8000:80"
